train:
  random_state: 123
  test_size: 0.2
  
model:
  n_estimators: 50
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  random_state: 123
  class_weight: balanced
  
data:
  target: Medal
  
paths:
  raw_data: data/raw/olympics_raw.csv
  cleaned_data: data/processed/olympics_cleaned.csv
  featured_data: data/processed/olympics_featured.csv
  model: models/random_forest_model.pkl
  metrics: models/metrics.json
